export default function RulesPage() {
  return (
    <main className="legal-page">
      <p className="eyebrow"><span>RULES</span> Updated July 15, 2026</p>
      <h1>Small stakes.<br/><em>Clear limits.</em></h1>

      <section><h2>Access status</h2><p>Lock In accepts new stakes only when the app shows enabled create or join actions. If those actions are unavailable, do not send tokens directly to the contract. Existing locks may still settle and claim while new stakes are paused.</p></section>
      <section><h2>Who may participate</h2><p>Lock In is for adults aged 18 or older, and access may be limited to an approved cohort. Do not participate where stake-based challenges are restricted or prohibited. Access to the app and the 1 USDC cap do not make participation lawful everywhere.</p></section>
      <section><h2>Two missions</h2><p>A Strava lock requires a challenge-named GPS Run that reaches the distance target. Manual, trainer, Strava-flagged, missing-GPS, and implausible-motion records are rejected. A Duolingo lock requires the participant to control the named profile and temporarily set its public Name to the exact wallet code, then counts only new cumulative XP above the baseline accepted when that wallet stakes. One Duolingo profile cannot back two wallets in the same lock, and the same XP range cannot be reused across days or locks.</p></section>
      <section><h2>What proof means</h2><p>Reclaim zkTLS proves what Strava or Duolingo returned over HTTPS and Lock In applies the published policy. It does not prove physical movement, human learning, or the absence of GPS spoofing, account sharing, bots, modified devices, or errors by an external service. Lock In reduces obvious and replayable fraud; no consumer data source can make cheating mathematically impossible.</p></section>
      <section><h2>Lock schedule</h2><p>A lock lasts 3 to 30 fixed 24-hour days and publishes its required wins, minimum crew, and maximum capacity before anyone joins. Registration closes at the displayed start. An activity must occur during its claimed lock day. Its proof may be submitted during that day or the following 24 hours, and only one completion can count per wallet and lock day.</p></section>
      <section><h2>Funds</h2><p>Every participant deposits the same amount, from 0.1 to 1 USDC per lock. The 1 USDC cap applies per participant, per lock. Monad gas is separate and is never refunded by the lock. Lock In charges no protocol fee.</p></section>
      <section><h2>Payouts</h2><p>If anyone reaches the target, finishers recover their stakes and split non-finishers&apos; stakes equally. If everyone or nobody finishes, each participant recovers their own stake. Cancelled and underfilled locks are refundable. Settlement and claims are permissionless onchain transactions.</p></section>
      <section><h2>Controls and risk</h2><p>The creator may cancel before the start. The contract owner may separately pause creation, joining, baseline evidence, or completion evidence and may cancel an unsettled lock only into refunds. If a completion-verification pause overlaps the period from lock start until the final proof deadline, that lock settles as a full participant refund. Pauses never block settlement or claims. The contracts have not been independently audited. Smart-contract, wallet, RPC, token, chain, provider, oracle, signer, and key failures can cause delay or loss.</p></section>
      <section><h2>Independent services</h2><p>Lock In is independent from Strava, Duolingo, Reclaim, Monad, Circle, wallets, RPC services, and explorers. Their names identify external services and do not imply approval, partnership, sponsorship, or endorsement. Their terms and availability apply separately.</p></section>
    </main>
  );
}
