export default function RulesPage() {
  return (
    <main className="legal-page">
      <p className="eyebrow"><span>RULES</span> Updated July 15, 2026</p>
      <h1>Small stakes.<br/><em>Clear limits.</em></h1>

      <section><h2>Access status</h2><p>Lock In accepts new stakes only when the app shows enabled create or join actions. If those actions are unavailable, do not send tokens directly to the contract. Existing locks may still settle and claim while new stakes are paused.</p></section>
      <section><h2>Who may participate</h2><p>Lock In is for adults aged 18 or older, and access may be limited to an approved cohort. Do not participate where stake-based challenges are restricted or prohibited. Access to the app and the 1 USDC cap do not make participation lawful everywhere.</p></section>
      <section><h2>The mission</h2><p>A lock requires a GPS Run that reaches the distance target and starts inside that day of the lock. You never rename anything: Lock In reads your runs straight from Strava. Manual, treadmill, Strava-flagged, missing-GPS and implausible-motion records are rejected. One run can only ever count once, in this lock or any other, and one Strava account cannot back two wallets in the same lock.</p></section>
      <section><h2>What verification means, and what it does not</h2><p>You authorise Lock In to read your activities through Strava&apos;s official API. Lock In&apos;s server reads the run, applies the published policy, and signs the result; that signature is what the contract accepts. So you are trusting Lock In&apos;s signing key, not only Strava. A stolen signing key could create completions that never happened. Verification also does not prove physical movement, or the absence of GPS spoofing, account sharing, bots, modified devices, or errors by Strava. Lock In reduces obvious and replayable fraud; no consumer data source can make cheating impossible.</p></section>
      <section><h2>Profiles and standings</h2><p>A Lock In handle is optional, public, unique while active, and independent from your Strava name. It must use 3-16 lowercase letters, numbers, or underscores and start with a letter. Changing or clearing it does not erase historical events; clearing only removes the current handle and releases it for reuse. The owner may hide an abusive handle from Lock In surfaces, but cannot remove the wallet&apos;s verified score or change its settlement rights.</p></section>
      <section><h2>Lock Score</h2><p>The first accepted completion for a wallet on each UTC day earns 10 overall Lock Score points. Each Strava identity can score only for the first wallet bound to it. A later valid completion from another wallet can still count for payout but earns no points. This limits multi-wallet farming; it does not prove a unique human across services. Extra stake, distance, XP, or multiple locks cannot multiply the daily score. Points are non-transferable, cannot be redeemed, and never affect winner status, settlement, or payouts.</p></section>
      <section><h2>Invites and high-fives</h2><p>A checksummed <code>LOCK-…</code> invite code represents a public Lock ID; it is not secret and does not bypass join rules. A joined participant may send one public high-five to a crewmate for a specific verified day. Reactions link both wallets, the lock, and day onchain. They award no points and have no payout effect.</p></section>
      <section><h2>Lock schedule</h2><p>A lock lasts 3 to 30 fixed 24-hour days and publishes its required runs, minimum crew, and maximum capacity before anyone joins. Registration closes at the displayed start. An activity must occur during its claimed lock day. Its proof may be submitted during that day or the following 24 hours, and only one completion can count per wallet and lock day.</p></section>
      <section><h2>Funds</h2><p>Every participant deposits the same amount, from 0.1 to 1 USDC per lock. The 1 USDC cap applies per participant, per lock. Monad gas is separate and is never refunded by the lock. Lock In charges no protocol fee.</p></section>
      <section><h2>Payouts</h2><p>If anyone reaches the target, finishers recover their stakes and split non-finishers&apos; stakes equally. If everyone or nobody finishes, each participant recovers their own stake. Cancelled and underfilled locks are refundable. Settlement and claims are permissionless onchain transactions.</p></section>
      <section><h2>Controls and risk</h2><p>The creator may cancel before the start. The contract owner may separately pause creation, joining, baseline evidence, or completion evidence and may cancel an unsettled lock only into refunds. If a completion-verification pause overlaps the period from lock start until the final proof deadline, that lock settles as a full participant refund. Pauses never block settlement or claims. The contracts have not been independently audited. Smart-contract, wallet, RPC, token, chain, provider, oracle, signer, and key failures can cause delay or loss.</p></section>
      <section><h2>Independent services</h2><p>Lock In is independent from Strava, Monad, Circle, wallets, RPC services, and explorers. Their names identify external services and do not imply approval, partnership, sponsorship, or endorsement. Their terms and availability apply separately.</p></section>
    </main>
  );
}
