export default function PrivacyPage() {
  const privacyEmail = process.env.NEXT_PUBLIC_PRIVACY_EMAIL?.trim();
  return (
    <main className="legal-page">
      <p className="eyebrow"><span>PRIVACY</span> Updated July 15, 2026</p>
      <h1>Minimal proof.<br/><em>Public settlement.</em></h1>

      <section><h2>Scope and contact</h2><p>This notice covers Lock In. Lock In has no offchain product-account database. An optional Lock In handle is public contract state, not a private account. The contact below handles privacy requests, security reports, and funds incidents.</p></section>
      <section><h2>Website and wallet</h2><p>The app reads the public address of the wallet you connect and public Monad state to display locks and prepare transactions. Before requesting admission or a Reclaim proof, the app asks you to sign a human-readable, five-minute wallet challenge. A successful signature creates a strictly necessary Secure, HttpOnly, SameSite=Strict browser cookie, bound to that wallet and website origin for up to 12 hours. The cookie contains a server-authenticated session token, not your signature or private key. Create and join admission uses your public wallet, action, Lock ID where applicable, nonce, and expiry. Hosting and RPC providers may process technical data such as IP address, device, request time, and logs under their own policies.</p></section>
      <section><h2>Social profile, score, and reactions</h2><p>You may choose a public Lock In handle for your wallet. It is optional and separate from your Strava or Duolingo identity. Setting, changing, or clearing it creates permanent public events. Clearing removes the active handle from normal Lock In surfaces and releases it for reuse, but cannot erase its history. Accepted mission days publish non-transferable Lock Score events: at most 10 overall points per wallet and UTC day, and each hashed service identity can score only for its first linked wallet in that mission. Another wallet&apos;s valid completion can still affect its Lock payout without earning points. This reduces multi-wallet farming but does not prove a unique human across services. The owner can hide an abusive handle without hiding the wallet or score. Points and high-fives never affect settlement or payouts.</p></section>
      <section><h2>Invite codes</h2><p>A <code>LOCK-…</code> invite code is derived from a public onchain Lock ID and includes a typo-detection checksum. It is intended to be shared. It is not secret, does not identify a person, and does not bypass wallet authentication, admission rules, capacity, or stake requirements.</p></section>
      <section><h2>Strava proof</h2><p>During verification, Reclaim and the verification function process the signed athlete marker, activity ID and title, sport, start time, distance, moving and elapsed time, elevation, GPS-presence status, trainer status, Strava flag status, proof time, Reclaim session, wallet, lock, and day. These fields can appear in the public proof transaction. Lock In does not request or publish your GPS route.</p></section>
      <section><h2>Duolingo proof</h2><p>You enter your existing Duolingo username; Lock In does not ask you to rename the profile. Reclaim creates two linked claims for its stable ID: an authenticated self-only request that discloses only the non-sensitive marker name <code>disable_social</code>, and a profile request that discloses stable ID, username, and cumulative XP. Proof time, Reclaim session, wallet, lock, and phase are also processed. These disclosed fields can appear in the public proof transaction. The pair shows that Duolingo authorized the active session for that profile&apos;s self-only endpoint and returned its XP snapshot; it does not prove legal identity, exclusive account use, who earned the XP, or human learning.</p></section>
      <section><h2>What Monad publishes</h2><p>The release design requires both a direct Reclaim witness proof and a short-lived backend attestation derived from the same proof set. The Reclaim SDK&apos;s onchain transform places signed <code>claimInfo.parameters</code>, signed <code>claimInfo.context</code>, claim metadata, and witness signatures in Monad transaction calldata. This calldata is public, copyable, and effectively permanent. Contract state and events also expose wallets, lock settings, membership, stakes, mission days, metrics, hashed identities and their mission-scoped scoring-wallet bindings, nullifiers, handles, moderation, scores, high-fives, settlement, and claims.</p></section>
      <section><h2>What stays out</h2><p>The top-level TEE attestation JWT checked by the server is excluded from the SDK&apos;s onchain transform. The GPS route and Duolingo privacy-setting values are not requested for disclosure. Lock In never asks for your Duolingo or Strava password. The app rejects any signed request containing a password, cookie, Authorization header, access token, API key, secret, privacy-setting value, or unexpected personal field before a wallet transaction can be prepared.</p></section>
      <section><h2>Offchain retention</h2><p>Lock In does not intentionally retain the full Reclaim SDK proof object in a product database after verification. That does not erase the transformed proof submitted in Monad calldata. The wallet-authentication cookie expires after at most 12 hours. If web access is restricted to approved wallets, the server compares the connected public wallet against that operator configuration; this controls only website and proof-API access, not direct contract calls. Reclaim, Vercel, RPC, wallet, email, and browser providers may retain operational data under their own policies. Support messages remain only as long as needed to respond, protect the service, meet obligations, or resolve an incident.</p></section>
      <section><h2>Purpose and rights</h2><p>Data is used to bind proof to the requesting wallet and lock, reject replay or impersonation, prepare transactions, render public state and rankings, route invites, display reactions, moderate abusive handles, control access, and answer support. Lock In does not sell a user profile. Depending on applicable law, you may request access, correction, deletion, restriction, or objection for offchain data controlled by Lock In. You can clear your active handle, but Lock In cannot erase its historical events, other Monad records, or data controlled by independent services.</p></section>
      <section><h2>Contact</h2><p>{privacyEmail ? <>Email <a href={`mailto:${privacyEmail}`}>{privacyEmail}</a> for a privacy request, incident, or support issue.</> : <>A public privacy contact must be configured before testers are invited.</>}</p></section>
      {!privacyEmail && <div className="legal-warning">Incomplete deployment: the public privacy contact is not configured.</div>}
    </main>
  );
}
