export default function PrivacyPage() {
  const privacyEmail = process.env.NEXT_PUBLIC_PRIVACY_EMAIL?.trim();
  return (
    <main className="legal-page">
      <p className="eyebrow"><span>PRIVACY</span> Updated July 15, 2026</p>
      <h1>Minimal proof.<br/><em>Public settlement.</em></h1>

      <section><h2>Scope and contact</h2><p>This notice covers Lock In. Lock In has no product account database. The contact below handles privacy requests, security reports, and funds incidents.</p></section>
      <section><h2>Website and wallet</h2><p>The app reads the public address of the wallet you connect and public Monad state to display locks and prepare transactions. Before requesting admission or a Reclaim proof, the app asks you to sign a human-readable, five-minute wallet challenge. A successful signature creates a strictly necessary Secure, HttpOnly, SameSite=Strict browser cookie, bound to that wallet and website origin for up to 12 hours. The cookie contains a server-authenticated session token, not your signature or private key. Create and join admission uses your public wallet, action, Lock ID where applicable, nonce, and expiry. Hosting and RPC providers may process technical data such as IP address, device, request time, and logs under their own policies.</p></section>
      <section><h2>Strava proof</h2><p>During verification, Reclaim and the verification function process the signed athlete marker, activity ID and title, sport, start time, distance, moving and elapsed time, elevation, GPS-presence status, trainer status, Strava flag status, proof time, Reclaim session, wallet, lock, and day. These fields can appear in the public proof transaction. Lock In does not request or publish your GPS route.</p></section>
      <section><h2>Duolingo proof</h2><p>You enter a Duolingo username and must control that profile well enough to temporarily set its public Name to the exact wallet-specific code at proof time. Reclaim and the verification function process stable profile ID, username, temporary Name code, cumulative XP, proof time, Reclaim session, wallet, lock, and phase. These fields can appear in the public proof transaction. The code demonstrates profile control at that time; it does not prove who earned the XP.</p></section>
      <section><h2>What a proof transaction publishes</h2><p>The release design requires both a direct Reclaim witness proof and a short-lived backend attestation derived from the same proof set. The Reclaim SDK&apos;s onchain transform places signed <code>claimInfo.parameters</code>, signed <code>claimInfo.context</code>, claim metadata, and witness signatures in Monad transaction calldata. This calldata is public, copyable, and effectively permanent even though Lock In does not copy all of it into contract state or events. Contract state and events also expose wallet addresses, lock settings, crew membership, stakes, mission, days, accepted metrics, hashed identities, nullifiers, settlement, and claims.</p></section>
      <section><h2>What stays out</h2><p>The top-level TEE attestation JWT checked by the server is excluded from the SDK&apos;s onchain transform. The GPS route is not requested. The app rejects any signed request containing a cookie, Authorization header, access token, API key, secret, or similar sensitive header before a wallet transaction can be prepared.</p></section>
      <section><h2>Offchain retention</h2><p>Lock In does not intentionally retain the full Reclaim SDK proof object in a product database after verification. That does not erase the transformed proof submitted in Monad calldata. The wallet-authentication cookie expires after at most 12 hours. If web access is restricted to approved wallets, the server compares the connected public wallet against that operator configuration; this controls only website and proof-API access, not direct contract calls. Reclaim, Vercel, RPC, wallet, email, and browser providers may retain operational data under their own policies. Support messages remain only as long as needed to respond, protect the service, meet obligations, or resolve an incident.</p></section>
      <section><h2>Purpose and rights</h2><p>Data is used only to bind a proof to the requesting wallet and lock, reject replay or impersonation, prepare the requested transaction, render public state, control access, and answer support. Lock In does not sell a user profile. Depending on applicable law, you may request access, correction, deletion, restriction, or objection for offchain data controlled by Lock In. Lock In cannot erase Monad records or data controlled by independent services.</p></section>
      <section><h2>Contact</h2><p>{privacyEmail ? <>Email <a href={`mailto:${privacyEmail}`}>{privacyEmail}</a> for a privacy request, incident, or support issue.</> : <>A public privacy contact must be configured before testers are invited.</>}</p></section>
      {!privacyEmail && <div className="legal-warning">Incomplete deployment: the public privacy contact is not configured.</div>}
    </main>
  );
}
