export const lockInAbi = [
  {
    type: "function",
    name: "nextPactId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "pacts",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "creator", type: "address" },
      { name: "startsAt", type: "uint64" },
      { name: "claimDeadline", type: "uint64" },
      { name: "stake", type: "uint96" },
      { name: "minDistanceMeters", type: "uint32" },
      { name: "participantCount", type: "uint32" },
      { name: "finisherCount", type: "uint32" },
      { name: "claimedCount", type: "uint32" },
      { name: "durationDays", type: "uint8" },
      { name: "requiredCompletions", type: "uint8" },
      { name: "minParticipants", type: "uint8" },
      { name: "challengeHash", type: "bytes32" },
      { name: "providerKey", type: "bytes32" },
      { name: "remainingPool", type: "uint256" },
      { name: "finalized", type: "bool" },
      { name: "cancelled", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "pactChallenges",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "joined",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "completionBitmap",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "completionCount",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "claimed",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }, { name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "VERSION",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "MAX_DAYS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "maxStake",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "stakeToken",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "evidenceSigner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "reclaim",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "createPact",
    stateMutability: "nonpayable",
    inputs: [
      { name: "stake", type: "uint96" },
      { name: "minDistanceMeters", type: "uint32" },
      { name: "durationDays", type: "uint8" },
      { name: "requiredCompletions", type: "uint8" },
      { name: "minParticipants", type: "uint8" },
      { name: "startsAt", type: "uint64" },
      { name: "claimDeadline", type: "uint64" },
      { name: "challenge", type: "string" },
    ],
    outputs: [{ name: "pactId", type: "uint256" }],
  },
  {
    type: "function",
    name: "joinPact",
    stateMutability: "nonpayable",
    inputs: [{ name: "pactId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "submitStravaProofs",
    stateMutability: "nonpayable",
    inputs: [
      { name: "pactId", type: "uint256" },
      { name: "dayIndex", type: "uint8" },
      { name: "challenge", type: "string" },
      {
        name: "proofs",
        type: "tuple[4]",
        components: [
          {
            name: "claimInfo",
            type: "tuple",
            components: [
              { name: "provider", type: "string" },
              { name: "parameters", type: "string" },
              { name: "context", type: "string" },
            ],
          },
          {
            name: "signedClaim",
            type: "tuple",
            components: [
              {
                name: "claim",
                type: "tuple",
                components: [
                  { name: "identifier", type: "bytes32" },
                  { name: "owner", type: "address" },
                  { name: "timestampS", type: "uint32" },
                  { name: "epoch", type: "uint32" },
                ],
              },
              { name: "signatures", type: "bytes[]" },
            ],
          },
        ],
      },
      { name: "expiresAt", type: "uint64" },
      { name: "validatorSignature", type: "bytes" },
    ],
    outputs: [{ name: "activityNullifier", type: "bytes32" }],
  },
  {
    type: "function",
    name: "finalizePact",
    stateMutability: "nonpayable",
    inputs: [{ name: "pactId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [{ name: "pactId", type: "uint256" }],
    outputs: [{ name: "amount", type: "uint256" }],
  },
  {
    type: "event",
    name: "IdentityBound",
    anonymous: false,
    inputs: [
      { indexed: true, name: "pactId", type: "uint256" },
      { indexed: true, name: "account", type: "address" },
      { indexed: true, name: "identityHash", type: "bytes32" },
    ],
  },
  {
    type: "event",
    name: "PactJoined",
    anonymous: false,
    inputs: [
      { indexed: true, name: "pactId", type: "uint256" },
      { indexed: true, name: "account", type: "address" },
    ],
  },
  {
    type: "event",
    name: "DayProved",
    anonymous: false,
    inputs: [
      { indexed: true, name: "pactId", type: "uint256" },
      { indexed: true, name: "account", type: "address" },
      { indexed: true, name: "dayIndex", type: "uint8" },
      { indexed: false, name: "activityNullifier", type: "bytes32" },
      { indexed: false, name: "distanceMeters", type: "uint256" },
      { indexed: false, name: "activityTimestamp", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "PactCreated",
    anonymous: false,
    inputs: [
      { indexed: true, name: "pactId", type: "uint256" },
      { indexed: true, name: "creator", type: "address" },
      { indexed: false, name: "stake", type: "uint256" },
      { indexed: false, name: "minDistanceMeters", type: "uint32" },
      { indexed: false, name: "durationDays", type: "uint8" },
      { indexed: false, name: "requiredCompletions", type: "uint8" },
      { indexed: false, name: "minParticipants", type: "uint8" },
      { indexed: false, name: "startsAt", type: "uint64" },
      { indexed: false, name: "claimDeadline", type: "uint64" },
      { indexed: false, name: "providerKey", type: "bytes32" },
      { indexed: false, name: "challenge", type: "string" },
    ],
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "uint8" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },
] as const;
